# Generated by Django 4.0.7 on 2022-08-26 13:31

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields

import integration_api.enums
import integration_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_address', models.CharField(max_length=70)),
                ('retail_api_key', models.CharField(max_length=100)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('period', enumchoicefield.fields.EnumChoiceField(default=integration_api.enums.TimeInterval['one_min'], enum_class=integration_api.enums.TimeInterval, max_length=15)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=integration_api.enums.TaskStatus['active'], enum_class=integration_api.enums.TaskStatus, max_length=8)),
                ('products', models.TextField(null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_address', models.CharField(max_length=70)),
                ('retail_api_key', models.CharField(max_length=100)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('period', enumchoicefield.fields.EnumChoiceField(default=integration_api.enums.TimeInterval['one_min'], enum_class=integration_api.enums.TimeInterval, max_length=15)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=integration_api.enums.TaskStatus['active'], enum_class=integration_api.enums.TaskStatus, max_length=8)),
                ('products', models.TextField(null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
